name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.8'

    - name: Install dependencies
      run: npm install &
    - name : Install python dependencies 
      run : |
        python -m pip install -r requirements.txt
          

    - name: Build the site
      run: npm run build
    - name : start GC
      run : | 
        python -m rsk.game_controller -s &

    - name: Start server
      run: |
        nohup npm start &
        sleep 10  # Attendre que le serveur démarre
        curl http://127.0.0.1:7070 

    - name: Display site content
      run: curl http://127.0.0.1:7070
