name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.8'  # Assurez-vous que la version de Python correspond à celle requise par votre script

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Installez les dépendances nécessaires, si vous avez un fichier requirements.txt

    - name: Run game controller
      run: |
        nohup python -m rsk.game_controller -s &
        sleep 10  # Attendre que le serveur démarre

    - name: Display site content
      run: curl http://127.0.0.1:7070
