name: Game Controller

on: [push]

jobs:
  run_controller:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.8'

    - name: Start Game Controller
      run: |
        python -m rsk.game_controller -s
